### PR TITLE
More thorough  check whether UIA can be used

### PR DESCRIPTION
**Pull request by robertschulze**
In order to prevent failed DLL loads e.g. under WINE

solves https://github.com/pywinauto/pywinauto/issues/957

### CODE REVIEW

**Comment by airelil** [comment]
Hi, not sure if that was intention, but this pull request for atspi branch of your private repo. If you want to contribute to the upstream create a pull request in pywinauto repo.

**Comment by robertschulze** [comment]
Oh yes, thanks for the heads-up!

**Comment by vasily-v-ryabov** [comment]
@airelil I think it looks like workaround (make pywinauto working on WINE with "win32" backend only). I'd prefer to find a way to load `UIAutomationCore.dll`. I'd recommend to try `ctypes.LoadLibrary(...)` first. I just don't have WINE setup right now.

**Comment by vasily-v-ryabov** [comment]
If `ctypes.LoadLibrary` works, it's rather comtypes issue. Otherwise it's more deep problem in CPython itself (or even in WINE).

**Comment by airelil** [comment]
Don't think it's only for wine. Should help to disable uia backend, generally, when the dll is not available for any reason.

**Pull request merged**
